# Generated by Django 2.1.3 on 2018-12-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181218_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default='Letters more than 200 will be sliced.'),
        ),
    ]
